spring.application.name=City-Builder
spring.datasource.url=jdbc:mysql://localhost:3306/citybuilder
spring.datasource.username=root
spring.datasource.password=Param@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true